### PR TITLE
Added instructions to download wtf paper

### PR DESCRIPTION
**Pull request by igorsyl**

### CODE REVIEW

**Review by xoloki — APPROVED** [review]
Can you also add a section for people who don't use gh?  Click on Actions, etc?

**Comment by igorsyl** [comment]
I tried but got no time. Ideally, we can add to CI to add a link to README. @sergey-shandar can help?

**Comment by xoloki** [comment]
@sergey-shandar please do what you can to fix doctest CI, and see if there's any way to get/publish a link to latest CI artifact

**Comment by sergey-shandar** [comment]
> @sergey-shandar please do what you can to fix doctest CI, and see if there's any way to get/publish a link to latest CI artifact

I propose to use GitHub Pages with GitHub Actions (Beta). It will build and deploy a website (including PDF). #87

**Comment by sergey-shandar** [comment]
> @sergey-shandar please do what you can to fix doctest CI, and see if there's any way to get/publish a link to latest CI artifact

WTFROST includes the README.md into comments and Doc Test assumes that all MarkDown code blocks in comments are Rust examples. Workaround: set a code block programming language, for example `shell` for this PR code blocks.

**Pull request merged**
